apiVersion: v1
kind: Pod
metadata:
  name: web
  namespace: default
spec:
  containers:
  - image: nginx:1.8
    imagePullPolicy: IfNotPresent
    name: web
    resources:
      limits:
        memory: 256Mi
        cpu: 512m
        ephemeral-storage: 10Mi
      requests:
        memory: 256Mi
        cpu: 256m
        ephemeral-storage: 10Mi
  restartPolicy: Always

