apiVersion: v1
kind: Pod
metadata:
  name: web
  namespace: default
spec:
  containers:
  - image: nginx:1.8
    imagePullPolicy: IfNotPresent
    name: web
    resources:
      limits:
        memory: 768Mi
      requests:
        memory: 768Mi
  restartPolicy: Always

