apiVersion: batch/v1
kind: Job
metadata:
  name: check-job
spec:
  template:
    spec:
      containers:
        - name: check
          image: mysql:5.7
          command:
            - /bin/sh
            - -c
            - echo "SHOW DATABASES" | mysql -h mysqlsrv -u root -ppassword
      restartPolicy: Never
